from enum import Enum


class ArtifactType(str, Enum):
    PROJECT_CONTEXT = "PROJECT_CONTEXT"
    REQUIREMENT_BASELINE = "REQUIREMENT_BASELINE"
    RESEARCH = "RESEARCH"
    EXISTING_SYSTEM_ANALYSIS = "EXISTING_SYSTEM_ANALYSIS"
    SOLUTION = "SOLUTION"
    PROCESS_FLOW = "PROCESS_FLOW"
    UI_PROTOTYPE = "UI_PROTOTYPE"
    DATABASE_DESIGN = "DATABASE_DESIGN"
    API_SPECIFICATION = "API_SPECIFICATION"
    TEST_SCENARIO = "TEST_SCENARIO"
    ACCEPTANCE_CRITERIA = "ACCEPTANCE_CRITERIA"
    DEVELOPMENT_TASK = "DEVELOPMENT_TASK"


class ArtifactStatus(str, Enum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"


APPROVAL_GATED_ARTIFACT_TYPES = frozenset(
    {
        ArtifactType.PROCESS_FLOW,
        ArtifactType.UI_PROTOTYPE,
        ArtifactType.DATABASE_DESIGN,
        ArtifactType.API_SPECIFICATION,
        ArtifactType.TEST_SCENARIO,
        ArtifactType.ACCEPTANCE_CRITERIA,
        ArtifactType.DEVELOPMENT_TASK,
    }
)
