from enum import Enum


class ExistingEvidenceType(str, Enum):
    USER_DESCRIPTION = "USER_DESCRIPTION"
    SOURCE_CODE_METADATA = "SOURCE_CODE_METADATA"
    DATABASE_SCHEMA = "DATABASE_SCHEMA"
    API_DOCUMENTATION = "API_DOCUMENTATION"
    EXISTING_DOCUMENTATION = "EXISTING_DOCUMENTATION"
    SCREENSHOT_DESCRIPTION = "SCREENSHOT_DESCRIPTION"
    PREVIOUS_ARTIFACT = "PREVIOUS_ARTIFACT"


class ExistingComponentType(str, Enum):
    MODULE = "MODULE"
    ENTITY = "ENTITY"
    MASTER_DATA = "MASTER_DATA"
    API = "API"
    TABLE = "TABLE"
    BUSINESS_RULE = "BUSINESS_RULE"
    INTEGRATION_POINT = "INTEGRATION_POINT"


class ChangeClassification(str, Enum):
    REUSE = "REUSE"
    MODIFY = "MODIFY"
    NEW = "NEW"
    DEPRECATE = "DEPRECATE"
