from enum import Enum


class OrchestratorStage(str, Enum):
    PROJECT_CONTEXT = "PROJECT_CONTEXT"
    REQUIREMENT_ANALYSIS = "REQUIREMENT_ANALYSIS"
    CLARIFICATION = "CLARIFICATION"
    REQUIREMENT_READY = "REQUIREMENT_READY"
    RESEARCH = "RESEARCH"
    EXISTING_SYSTEM_ANALYSIS = "EXISTING_SYSTEM_ANALYSIS"
    SOLUTION_DESIGN = "SOLUTION_DESIGN"
    USER_APPROVAL = "USER_APPROVAL"
    FLOW_UI_TECHNICAL_DESIGN = "FLOW_UI_TECHNICAL_DESIGN"
    QA = "QA"
    SA_REVIEW = "SA_REVIEW"
    REVISION_LOOP = "REVISION_LOOP"
    HANDOFF_READY = "HANDOFF_READY"
    COMPLETED = "COMPLETED"


class OrchestratorStatus(str, Enum):
    ACTIVE = "ACTIVE"
    WAITING_USER_ACTION = "WAITING_USER_ACTION"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"


class OrchestratorExecutionStatus(str, Enum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    WAITING = "WAITING"
    FAILED = "FAILED"


STAGE_AGENT = {
    OrchestratorStage.REQUIREMENT_ANALYSIS: "REQUIREMENT_ANALYST",
    OrchestratorStage.RESEARCH: "RESEARCH_AGENT",
    OrchestratorStage.EXISTING_SYSTEM_ANALYSIS: "EXISTING_SYSTEM_ANALYST",
    OrchestratorStage.SOLUTION_DESIGN: "SOLUTION_ANALYST",
    OrchestratorStage.FLOW_UI_TECHNICAL_DESIGN: "DESIGN_SPECIALISTS",
    OrchestratorStage.QA: "QA_ANALYST",
    OrchestratorStage.SA_REVIEW: "SA_REVIEWER",
    OrchestratorStage.REVISION_LOOP: "ARTIFACT_OWNER",
    OrchestratorStage.HANDOFF_READY: "DEVELOPMENT_PLANNER",
}
